openapi: 3.0.3
info:
  title: QuestionGeneratorOpenApi
  version: 1.0.0
  description: OpenApi for question-generator project. Integration between Spring, Python and React projects.
servers:
  - url: http://localhost:8080

paths:
  /api/send-text:
    post:
      tags:
        - question-generator
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadTextForm'
      description: Send text for question generation.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadTextDto'
        '400':
          description: Bad request
        '500':
          description: Server error

components:
  schemas:
    UploadTextForm:
      type: object
      properties:
        text:
          type: string

    UploadTextDto:
      type: object
      properties:
        text:
          type: string

    QuestionGeneratorRequest:
      type: object
      properties:
        text:
          type: string

    QuestionGeneratorResponse:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        distractors:
          type: array
          items:
            type: string